version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: https://github.com/efnushtaev/portainer-demo-server.git
    container_name: my-app-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=your_database_url
      - API_PORT=3001
    expose:
      - "3001"  # Открываем порт только для внутренней сети Docker
    networks:
      - fullstack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"] # Или wget, или node-скрипт
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service (только сборка статики)
  frontend:
    build:
      context: https://github.com/efnushtaev/portainer-demo-client.git
    container_name: my-app-frontend-builder
    image: portainer-demo-docker-compose-frontend  
    restart: "no"  # Этот контейнер не должен перезапускаться
    networks:
      - fullstack-network
    # Не публикуем порты, контейнер используется только для сборки

  # Nginx reverse proxy
  nginx:
    build:
      context: .
    container_name: my-app-nginx
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS (если добавите SSL)
    depends_on:
      - backend
      - frontend
    networks:
      - fullstack-network
    # volumes:
      # Монтируем статику из фронтенда в nginx
      # - frontend-static:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# Volumes для хранения статики фронтенда
# volumes:
  # frontend-static:
    # driver: local

# Сеть для коммуникации между сервисами
networks:
  fullstack-network:
    driver: bridge